name: bloc_arch
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  json_annotation: ^4.7.0
  dartz: ^0.10.1
  connectivity_plus: ^3.0.2
  equatable: ^2.0.5
  http: ^0.13.5
  font_awesome_flutter: ^10.3.0
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.2.0
  built_value: ^8.4.3
  built_collection: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  bloc_test: ^9.1.0
  json_serializable: ^6.5.4
  build_runner: ^2.3.0
  freezed: ^2.2.0
  built_value_generator: ^8.4.3

flutter:
  uses-material-design: true

  assets:
    - assets/
