// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUQRDvmKQQJ7_wVmdpbC2UlCHIK9PTWVw',
    appId: '1:566213404382:web:b1c900d966243b3424844f',
    messagingSenderId: '566213404382',
    projectId: 'bloc-arch',
    authDomain: 'bloc-arch.firebaseapp.com',
    storageBucket: 'bloc-arch.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeUMz4gHQDhtwF8zLxDzRIdB4d-POMDmA',
    appId: '1:566213404382:android:08cd9a7f50dd1c6b24844f',
    messagingSenderId: '566213404382',
    projectId: 'bloc-arch',
    storageBucket: 'bloc-arch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKSSBSOx3XPsFNlOwLgFF69RwccOrWoNs',
    appId: '1:566213404382:ios:84462871cb9b0f2f24844f',
    messagingSenderId: '566213404382',
    projectId: 'bloc-arch',
    storageBucket: 'bloc-arch.appspot.com',
    iosClientId: '566213404382-tmrfv9k6j8s58efajhc8kukrfm092gis.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocArch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKSSBSOx3XPsFNlOwLgFF69RwccOrWoNs',
    appId: '1:566213404382:ios:84462871cb9b0f2f24844f',
    messagingSenderId: '566213404382',
    projectId: 'bloc-arch',
    storageBucket: 'bloc-arch.appspot.com',
    iosClientId: '566213404382-tmrfv9k6j8s58efajhc8kukrfm092gis.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocArch',
  );
}
